export const USER_ADDED = 'USER_ADDED';
export const USER_CHANGED = 'USER_CHANGED';
export const USER_REMOVED = 'USER_REMOVED';

export const GROUP_ADDED = 'GROUP_ADDED';
export const GROUP_CHANGED = 'GROUP_CHANGED';
export const GROUP_REMOVED = 'GROUP_REMOVED';

export const BOARD_MESSAGE_ADDED = 'BOARD_MESSAGE_ADDED';
export const BOARD_MESSAGE_CHANGED = 'BOARD_MESSAGE_CHANGED';
export const BOARD_MESSAGE_REMOVED = 'BOARD_MESSAGE_REMOVED';

export const GROUP_MESSAGE_ADDED = 'GROUP_MESSAGE_ADDED';
export const GROUP_MESSAGE_CHANGED = 'GROUP_MESSAGE_CHANGED';
export const GROUP_MESSAGE_REMOVED = 'GROUP_MESSAGE_REMOVED';
export const GROUP_UNSUBSCRIBED = 'GROUP_UNSUBSCRIBED';

export const LOGOUT = 'LOGOUT';
export const LOGIN = 'LOGIN';
export const UPDATE_AVATAR = 'UPDATE_AVATAR';
